apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rails-app-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.ingress.entrypoint }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - path: /rails
        pathType: Prefix
        backend:
          service:
            name: rails-app-service
            port:
              number: 80
      - path: /assets
        pathType: Prefix
        backend:
          service:
            name: rails-app-service
            port:
              number: 80