apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rails-sqlite-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
