apiVersion: v1
kind: Service
metadata:
  name: rails-app-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    name: http
    app: rails-web